<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link rel="stylesheet" href="../api/css/main.css" />
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    </head>
    <body>
        <form id="productForm" action= "form_action.php" method= "post" enctype="multipart/form-data">
	
			<div class="mainArea">

				<label>Name:</label>
				<input type="text" id="name" name="name" required>

				<label>Price:</label>
				<input type="text" id="price" name="price" required>

				<input type="file" name="pic" id = "pic" accept="image/*">

				<button id="btnSave">Save</button>

			</div>

		</form>
    </body>
</html>
